export const meta = {
  name: 'floodguard-leaf-artifacts',
  description: 'Fan out independent leaf artifacts for FloodGuard AI: architecture docs, README, Docker files, gitignore. These are descriptive and do not depend on executable code logic.',
  phases: [{ title: 'LeafArtifacts' }]
}

phase('LeafArtifacts')

// Each agent writes its own files via the Write tool. Prompts are fully self-contained.
const results = await parallel([
  agent('Write docs/architecture.md for the FloodGuard AI project. Create file at /Users/akashsj/floodguard-ai/docs/architecture.md. Content must cover: (1) System overview — real-time weather/forecast-driven urban flood prediction & early-warning platform (NO IoT/sensors). (2) Data flow: Weather provider (Open-Meteo, no API key) -> WeatherService -> feature engineering (rainfall accumulations 1h/3h/6h/12h/24h + forecast accumulations + zone static features) -> ML model (RandomForest/XGBoost) -> risk engine -> map/alerts/recommendations/simulator. (3) Component breakdown for backend (FastAPI: api/, services/, models/, ml/, utils/), ml/ training pipeline, frontend (React+Vite+Tailwind+React Leaflet+Recharts). (4) Database tables: User, Zone, WeatherObservation, WeatherForecast, Prediction, Alert, FloodEvent, EmergencyResource. (5) Risk levels: 0-20 LOW, 20-40 MODERATE, 40-60 HIGH, 60-80 VERY HIGH, 80-100 CRITICAL. (6) Responsible-AI note: decision-support only, not official warnings. Use markdown headings, mermaid-style ASCII diagrams, and professional tone. It is for a hackathon README/docs.', { label: 'docs-architecture', phase: 'LeafArtifacts' }),

  agent('Write a comprehensive professional README.md at /Users/akashsj/floodguard-ai/README.md for the FloodGuard AI hackathon project. Include these exact sections with real content (not placeholders): Title + subtitle "Real-Time AI Urban Flood Prediction, Early Warning and Decision Support Platform"; Problem; Solution; Features (weather-driven prediction, risk map, forecast risk, explainable AI, alerts, recommendations, what-if simulator, citizen mode, analytics, demo mode); Architecture (monorepo: backend FastAPI + ml training pipeline + frontend React); Weather Data flow (Open-Meteo provider behind WeatherService, no API key, DEMO MODE fallback); ML Pipeline (features: rainfall_1h/3h/6h/12h/24h, forecast_rainfall_1h/3h/6h/12h, temperature, humidity, pressure, wind_speed, elevation, slope, drainage_capacity, impervious_surface, population_density, historical_flood_frequency; target: flood; models RandomForest then XGBoost; metrics Accuracy/Precision/Recall/F1/ROC-AUC/Confusion Matrix with emphasis on recall/false-negatives); GIS methodology (Leaflet + GeoJSON zones colored by risk); API documentation listing EXACTLY these endpoints: GET /api/health, GET /api/weather/current?lat=&lon=, GET /api/weather/forecast?lat=&lon=, GET /api/weather/rainfall?lat=&lon=, POST /api/predict {zone_id, scenario?}, GET /api/zones, GET /api/zones/{zone_id}, GET /api/alerts?risk=&status=, POST /api/alerts/{alert_id}/acknowledge, POST /api/simulation {zone_id, adjustments}, GET /api/analytics; Installation (backend: python3 -m venv venv; source venv/bin/activate; pip install -r requirements.txt; uvicorn app.main:app --reload on port 8000. frontend: npm install; npm run dev on 5173); Environment Variables (WEATHER_PROVIDER=openmeteo, DATABASE_URL, CORS_ORIGINS, optional WEATHER_API_KEY for other providers); Local development; Demo Mode (toggle in UI, works offline); Testing (pytest in backend, npm test in frontend); Deployment (frontend Vercel, backend Render/Railway/Cloud Run, DB PostgreSQL/Supabase, Docker compose); Limitations; Responsible AI (decision-support only, does not replace official disaster warnings, forecasts have uncertainty); Future Scope; plus a Screenshots section placeholder. Keep it polished and accurate to the structure above.', { label: 'readme', phase: 'LeafArtifacts' }),

  agent('Write a docker-compose.yml at /Users/akashsj/floodguard-ai/docker-compose.yml for FloodGuard AI. Define three services: (1) backend — build from ./backend, Dockerfile named Dockerfile, expose port 8000, environment DATABASE_URL=sqlite:///./floodguard.db and CORS_ORIGINS=http://localhost:5173 and WEATHER_PROVIDER=openmeteo, command "uvicorn app.main:app --host 0.0.0.0 --port 8000", volumes for the sqlite db. (2) frontend — build from ./frontend, Dockerfile named Dockerfile, expose 5173, environment VITE_API_URL=http://localhost:8000, command "npm run dev -- --host 0.0.0.0". (3) db — use postgres:16 if desired OR comment that dev uses SQLite. Keep it simple and working for local Docker. Use yaml with services, build contexts, ports, environment. Add a top comment that dev uses SQLite and Docker is optional for demos.', { label: 'compose', phase: 'LeafArtifacts' }),

  agent('Write two Dockerfiles. (1) /Users/akashsj/floodguard-ai/backend/Dockerfile — python:3.11-slim base, set WORKDIR /app, copy requirements.txt then RUN pip install --no-cache-dir -r requirements.txt, copy the rest of backend (COPY . .), EXPOSE 8000, CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]. (2) /Users/akashsj/floodguard-ai/frontend/Dockerfile — use node:20-alpine, WORKDIR /app, copy package.json and package-lock.json (if present) then RUN npm install, copy . ., EXPOSE 5173, CMD ["npm","run","dev","--","--host","0.0.0.0"]. Also create /Users/akashsj/floodguard-ai/frontend/.dockerignore containing node_modules and dist. Make the backend Dockerfile robust if requirements.txt present.', { label: 'dockerfiles', phase: 'LeafArtifacts' }),

  agent('Write /Users/akashsj/floodguard-ai/.gitignore covering: Python (__pycache__/, *.pyc, venv/, .venv/, *.egg-info/, .pytest_cache/, *.db, floodguard.db, __pycache__), Node/JS (node_modules/, dist/, .vite/, npm-debug.log*), environment files (.env, .env.local, but keep .env.example tracked — so only ignore .env and secret files; do NOT ignore .env.example), ML artifacts (ml/data/*.csv is sample data — ignore large generated csvs but the repo uses sample csvs; ignore *.pkl? NO — the trained model flood_model.pkl is needed; but it is generated — add it to gitignore AND note it is generated by ml/train.py. Add backend/app/ml/*.pkl to gitignore). Also ignore .DS_Store, *.log, .idea/, .vscode/, coverage. Keep it concise and correct (do not ignore source files or .env.example).', { label: 'gitignore', phase: 'LeafArtifacts' })
])

return { written: results.map((r, i) => `artifact-${i}`).filter(Boolean).length }
